config/routes.rb
Rails.application.routes.draw do
  resources :locations
  root 'locations#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord

  geocoded_by :my_location
  after_validation :geocode
  validates :address, presence: true
  validates :city, presence: true

 def my_location
    "#{address}, #{city}, GA"
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]
  include ApplicationHelper

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json

  def show
    @buses = HTTParty.get('http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus')

    @bus_count = 0

    @nearby_buses = []

    @buses.each do |bus|
      if nearby(@location.longitude, @location.latitude, 
        bus["LONGITUDE"].to_f, bus["LATITUDE"].to_f)
        @bus_count += 1
        @nearby_buses.push(bus)
      end
    end

    if valid_location(@location) #Checks to see if there are coordinates
      @buses = HTTParty.get('http://developer.itsmarta.com/BRDRestService/RestBusRealTimeService/GetAllBus')
      @bus_count = 0
      @nearby_buses = []

      @buses.each do |bus|
        if nearby(@location.longitude, @location.latitude, bus['LONGITUDE'].to_f, bus['LATITUDE'].to_f)
          @bus_count +=1
          @nearby_buses.push(bus)
        end
      end 
    else
      redirect_to root_path, notice: "Location not found, try a new address." 
    end      
end

 

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
      params.require(:location).permit(:address, :city, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nearby(lng1, lat1, lng2, lat2)
    if (lng1-lng2).abs <= 0.01 && (lat1-lat2).abs <= 0.01
      return true
    else
      return false
    end
  end

  def valid_location(location)
	  if location.latitude == nil || location.longitude == nil
        return false
	   else
		return true	
	   end
  end	
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MartaNearMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <%= yield %>
    </div>

    <script type="text/javascript" 
    src="https://maps.googleapis.com/maps/api/js?key=<%= Figaro.env.google_api_key %>">
    </script>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, 
    placeholder: "Address or Approx. Location"%>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, 
    placeholder: "City"%>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>City</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.city %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>Is a Bus Nearby?</h1>

<p>
  Give us your address or approximate location
  (<em>I'm at the corner of...</em>), and we'll
  let you know if there's a bus in vicinity!
</p>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @location.city %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>


<h2>You Are Currently Standing At...</h2>
<p>
  <%= @location.my_location %>
</p>

<h2>The Closest Buses Are...</h2>

    <% if @bus_count == 0 %>
      <p>
        ...not really that close. Better order an Uber. Or Lyft. 
        Or call a friend. Or just give up and go back inside and 
        watch some TV. Going places is overrated.
        </p>
    <% else %>
   <% end %>


	<% @nearby_buses.each_with_index do |bus, index| %>
	<p>
		<strong>Route:</strong> <%= bus["ROUTE"] %><br />
		<strong>Vehicle:</strong> <%= bus["VEHICLE"] %><br />
		<strong>Next Stop:</strong> <%= bus["TIMEPOINT"] %>
	</p>
<script>

$(document).ready(function (){
    function initialize(){

     var userCoords = new google.maps.LatLng(<%= @location.latitude %>,         <%= @location.longitude %>);

     var busCoords = new google.maps.LatLng(<%= bus["LATITUDE"] %>, <%= bus["LONGITUDE"] %>);

     var mapOptions = {
	     center: userCoords,
	     zoom: 13,
	     scrollwheel: false
         };
		      
     var map = new google.maps.Map(document.getElementById('map-canvas<%= index %>'), mapOptions);

      
      // This is the text for our bus
     var contentStringBus = "A bus is here!"; 

      // This is the text for our user
     var contentStringUser = "You are here!";


      // This is the marker that shows where the bus is
     var busMarker = new google.maps.Marker({
        position: busCoords,
        map: map,
	    animation: google.maps.Animation.DROP
      });

      // This is the marker for our users position
     var userMarker = new google.maps.Marker({
        position: userCoords,
    	map: map,
	    animation: google.maps.Animation.DROP
      });

     // Info window and event listener for the bus
     var infoWindowBus = new google.maps.InfoWindow({
        content: contentStringBus
      });

      google.maps.event.addListener(busMarker, 'click', function() {
        infoWindowBus.open(map, busMarker);
      });

       // Info window and event listener for the user
     var infoWindowUser = new google.maps.InfoWindow({
        content: contentStringUser
      });

      google.maps.event.addListener(userMarker, 'click', function() {
        infoWindowUser.open(map, userMarker);
      });

    }
  
  google.maps.event.addDomListener(window, 'load', initialize);
  });
		
</script>

<div class="bus-map" id="map-canvas<%= index %>">
</div>

<% end %>
<%= link_to "Actually, I'm at...", root_path %>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>